#!/usr/bin/env python3
"""Generate synthetic CSV files in Synthea-compatible format for the RWE Studio demo.

IMPORTANT — THIS IS NOT SYNTHEA OUTPUT:
  These files are generated by a custom Python script, not by the Synthea
  open-source patient simulator (https://github.com/synthetichealth/synthea).
  They use the same CSV column layout as Synthea so that the RWE Studio ingestion
  pipeline can load them, but they were not produced by Synthea's Java engine.

  When ingesting these files, use:
      evidence-studio ingest --data-source custom_synthetic_demo --data-dir <output-dir>

  All patient records are entirely synthetic.  No real patient information was
  used or is present.  Results derived from this data must not be used for
  clinical decisions, regulatory submissions, or public health reporting.

Usage:
    python scripts/generate_demo_data.py --output-dir data/raw
    python scripts/generate_demo_data.py --output-dir data/raw --seed 99 --population 500 --force
"""

from __future__ import annotations

import argparse
import csv
import random
import sys
import uuid
from datetime import date, timedelta
from pathlib import Path

# ── Reference data ────────────────────────────────────────────────────────────

RACES = ["white", "black", "asian", "other", "native"]
RACE_W = [0.60, 0.18, 0.10, 0.08, 0.04]
ETHNICITIES = ["nonhispanic", "hispanic"]
ETHNICITY_W = [0.82, 0.18]
GENDERS = ["M", "F"]
FIRST_M = [
    "James",
    "John",
    "Robert",
    "Michael",
    "William",
    "David",
    "Richard",
    "Joseph",
    "Thomas",
    "Charles",
]
FIRST_F = [
    "Mary",
    "Patricia",
    "Jennifer",
    "Linda",
    "Barbara",
    "Elizabeth",
    "Susan",
    "Jessica",
    "Sarah",
    "Karen",
]
LAST = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Wilson",
    "Martinez",
]
CITIES = ["Boston", "Springfield", "Worcester", "Cambridge", "Lowell"]
ZIPS = ["02101", "02102", "02103", "02104", "02105"]
ORGS = [str(uuid.uuid4()).upper() for _ in range(5)]
PROVIDERS = [str(uuid.uuid4()).upper() for _ in range(20)]
PAYERS = [str(uuid.uuid4()).upper() for _ in range(3)]

# ── SNOMED conditions ─────────────────────────────────────────────────────────

C_T2DM = ("44054006", "Type 2 diabetes mellitus")
C_T1DM = ("46635009", "Type 1 diabetes mellitus")
C_GDM = ("11687002", "Gestational diabetes mellitus")
C_PREG = ("77386006", "Pregnant")
C_HTN = ("59621000", "Essential hypertension")
C_CKD = ("709044004", "Chronic kidney disease stage 3")
C_CVD = ("53741008", "Coronary arteriosclerosis")
C_OBE = ("414916001", "Obesity (BMI 30+)")
C_AST = ("195967001", "Asthma")
C_HYPO = ("40930008", "Hypothyroidism")
C_BACK = ("161891005", "Chronic low back pain")

# ── GLP-1 medications (Synthea-compatible format) ─────────────────────────────

GLP1 = [
    ("860975", "semaglutide 1 MG/ML Injectable Solution"),
    ("2200997", "liraglutide 6 MG/ML Injectable Solution"),
    ("897120", "dulaglutide 1.5 MG/0.5ML Injectable Solution"),
    ("966787", "exenatide 250 UG/ML Injectable Solution"),
]

DM_MEDS = [
    ("860974", "metformin 500 MG Oral Tablet"),
    ("978015", "glipizide 5 MG Oral Tablet"),
    ("748856", "sitagliptin 100 MG Oral Tablet"),
    ("977860", "empagliflozin 10 MG Oral Tablet"),
]
OTHER_MEDS = [
    ("993671", "amlodipine 10 MG Oral Tablet"),
    ("1035921", "atorvastatin 40 MG Oral Tablet"),
    ("979485", "lisinopril 20 MG Oral Tablet"),
    ("1098714", "omeprazole 20 MG Oral Capsule"),
    ("897399", "aspirin 81 MG Oral Tablet"),
    ("308460", "hydrochlorothiazide 25 MG Oral Tablet"),
]

# ── Encounter types ────────────────────────────────────────────────────────────

ENC_AMB = ("ambulatory", "185345009", "Encounter for check-up")
ENC_WELL = ("wellness", "308646001", "Preventive care visit")
ENC_OUTPT = ("outpatient", "390906007", "Outpatient follow-up visit")
ENC_ED = ("emergency", "50849002", "Emergency room admission")
ENC_IP = ("inpatient", "32485007", "Inpatient hospital admission")
ENC_AMBA = [ENC_AMB, ENC_WELL, ENC_OUTPT]

# ── LOINC observations ────────────────────────────────────────────────────────

OBS_HBA1C = ("4548-4", "Hemoglobin A1c/Hemoglobin.total in Blood", "%")
OBS_BMI = ("39156-5", "Body mass index (BMI) [Ratio]", "kg/m2")
OBS_SBP = ("8480-6", "Systolic blood pressure", "mm[Hg]")
OBS_DBP = ("8462-4", "Diastolic blood pressure", "mm[Hg]")
OBS_GLUC = ("2345-7", "Glucose [Mass/volume] in Serum or Plasma", "mg/dL")
OBS_CREAT = ("2160-0", "Creatinine [Mass/volume] in Serum or Plasma", "mg/dL")


# ── Generator class (holds all accumulated row lists) ─────────────────────────


class _Generator:
    def __init__(self) -> None:
        self.patients: list[dict] = []
        self.encounters: list[dict] = []
        self.conditions: list[dict] = []
        self.medications: list[dict] = []
        self.observations: list[dict] = []

    # ── Row factories ─────────────────────────────────────────────────────────

    def _uid(self) -> str:
        return str(uuid.uuid4()).upper()

    def _jitter(self, d: date, lo: int, hi: int) -> date:
        return d + timedelta(days=random.randint(lo, hi))

    def _ts(self, d: date, hour: int = 9) -> str:
        return f"{d.isoformat()}T{hour:02d}:{random.randint(0, 59):02d}"

    def add_patient(
        self, patient_id: str, birth_date: date, death_date: date | None = None
    ) -> None:
        gender = random.choice(GENDERS)
        self.patients.append(
            {
                "Id": patient_id,
                "BIRTHDATE": birth_date.isoformat(),
                "DEATHDATE": death_date.isoformat() if death_date else "",
                "SSN": f"999-{random.randint(10, 99)}-{random.randint(1000, 9999)}",
                "DRIVERS": "",
                "PASSPORT": "",
                "PREFIX": "Mr." if gender == "M" else "Ms.",
                "FIRST": random.choice(FIRST_M if gender == "M" else FIRST_F),
                "LAST": random.choice(LAST),
                "SUFFIX": "",
                "MAIDEN": "",
                "MARITAL": random.choice(["M", "S"]),
                "RACE": random.choices(RACES, weights=RACE_W)[0],
                "ETHNICITY": random.choices(ETHNICITIES, weights=ETHNICITY_W)[0],
                "GENDER": gender,
                "BIRTHPLACE": random.choice(CITIES),
                "ADDRESS": f"{random.randint(1, 999)} Main St",
                "CITY": random.choice(CITIES),
                "STATE": "MA",
                "COUNTY": "Suffolk",
                "FIPS": "25025",
                "ZIP": random.choice(ZIPS),
                "LAT": f"{42.0 + random.uniform(-0.4, 0.4):.4f}",
                "LON": f"{-71.0 + random.uniform(-0.4, 0.4):.4f}",
                "HEALTHCARE_EXPENSES": f"{random.uniform(1000, 50000):.2f}",
                "HEALTHCARE_COVERAGE": f"{random.uniform(500, 20000):.2f}",
                "INCOME": str(random.randint(20000, 150000)),
            }
        )

    def add_encounter(
        self,
        patient_id: str,
        d: date,
        enc_tuple: tuple,
        reason_code: str = "",
        reason_desc: str = "",
    ) -> str:
        enc_id = self._uid()
        cls, code, desc = enc_tuple
        if cls == "emergency":
            stop_ts = self._ts(d, random.randint(14, 22))
        elif cls == "inpatient":
            stop_ts = (d + timedelta(days=random.randint(1, 5))).isoformat() + "T10:00"
        else:
            stop_ts = self._ts(d, random.randint(10, 17))
        self.encounters.append(
            {
                "Id": enc_id,
                "START": self._ts(d, 8 if cls == "inpatient" else 9),
                "STOP": stop_ts,
                "PATIENT": patient_id,
                "ORGANIZATION": random.choice(ORGS),
                "PROVIDER": random.choice(PROVIDERS),
                "PAYER": random.choice(PAYERS),
                "ENCOUNTERCLASS": cls,
                "CODE": code,
                "DESCRIPTION": desc,
                "BASE_ENCOUNTER_COST": f"{random.uniform(80, 800):.2f}",
                "TOTAL_CLAIM_COST": f"{random.uniform(200, 5000):.2f}",
                "PAYER_COVERAGE": f"{random.uniform(50, 3000):.2f}",
                "REASONCODE": reason_code,
                "REASONDESCRIPTION": reason_desc,
            }
        )
        return enc_id

    def add_condition(
        self, patient_id: str, enc_id: str, d: date, cond: tuple, stop_date: date | None = None
    ) -> None:
        code, desc = cond
        self.conditions.append(
            {
                "START": d.isoformat(),
                "STOP": stop_date.isoformat() if stop_date else "",
                "PATIENT": patient_id,
                "ENCOUNTER": enc_id,
                "CODE": code,
                "DESCRIPTION": desc,
                "SYSTEM": "SNOMED-CT",
                "DISPLAY": desc,
                "SNOMED_DESCRIPTION": desc,
                "STATUS": "active",
            }
        )

    def add_medication(
        self,
        patient_id: str,
        enc_id: str,
        d: date,
        med: tuple,
        stop: date | None = None,
        reason_code: str = "",
        reason_desc: str = "",
    ) -> None:
        code, desc = med
        self.medications.append(
            {
                "START": d.isoformat(),
                "STOP": stop.isoformat() if stop else "",
                "PATIENT": patient_id,
                "ENCOUNTER": enc_id,
                "CODE": code,
                "DESCRIPTION": desc,
                "REASONCODE": reason_code,
                "REASONDESCRIPTION": reason_desc,
                "DISPENSES": str(random.randint(4, 24)),
                "BASE_COST": f"{random.uniform(5, 400):.2f}",
                "PAYER_COVERAGE": f"{random.uniform(3, 300):.2f}",
                "TOTALCOST": f"{random.uniform(10, 500):.2f}",
            }
        )

    def add_observation(
        self, patient_id: str, enc_id: str, d: date, obs: tuple, value: float
    ) -> None:
        code, desc, unit = obs
        self.observations.append(
            {
                "DATE": d.isoformat(),
                "PATIENT": patient_id,
                "ENCOUNTER": enc_id,
                "CODE": code,
                "DESCRIPTION": desc,
                "VALUE": f"{value:.1f}",
                "UNITS": unit,
                "TYPE": "numeric",
            }
        )

    # ── Patient builders ──────────────────────────────────────────────────────

    def build_enrolled(self, index_date: date, birth_date: date) -> str:
        """Patient that passes every inclusion/exclusion criterion."""
        pid = self._uid()
        self.add_patient(pid, birth_date)

        t2dm_date = self._jitter(index_date, -1825, -365)
        bl_enc_id = self.add_encounter(pid, t2dm_date, random.choice(ENC_AMBA))
        self.add_condition(pid, bl_enc_id, t2dm_date, C_T2DM)

        if random.random() < 0.70:
            self.add_condition(pid, bl_enc_id, t2dm_date, C_OBE)
        if random.random() < 0.80:
            self.add_medication(
                pid,
                bl_enc_id,
                t2dm_date,
                random.choice(DM_MEDS),
                stop=index_date - timedelta(days=random.randint(0, 30)),
                reason_code=C_T2DM[0],
                reason_desc=C_T2DM[1],
            )

        visit = t2dm_date + timedelta(days=90)
        while visit < index_date - timedelta(days=30):
            enc_id = self.add_encounter(pid, visit, random.choice(ENC_AMBA))
            if random.random() < 0.75:
                self.add_observation(
                    pid, enc_id, visit, OBS_HBA1C, round(random.uniform(6.5, 11.0), 1)
                )
            if random.random() < 0.85:
                self.add_observation(
                    pid, enc_id, visit, OBS_BMI, round(random.uniform(27.0, 42.0), 1)
                )
            if random.random() < 0.60:
                self.add_observation(pid, enc_id, visit, OBS_SBP, float(random.randint(120, 165)))
            visit += timedelta(days=90)

        if random.random() < 0.55:
            htn_date = self._jitter(t2dm_date, 0, (index_date - t2dm_date).days)
            htn_enc_id = self.add_encounter(pid, htn_date, random.choice(ENC_AMBA))
            self.add_condition(pid, htn_enc_id, htn_date, C_HTN)
            self.add_medication(
                pid,
                htn_enc_id,
                htn_date,
                ("979485", "lisinopril 20 MG Oral Tablet"),
                reason_code=C_HTN[0],
                reason_desc=C_HTN[1],
            )
        if random.random() < 0.20:
            ckd_date = self._jitter(t2dm_date, 180, min(730, (index_date - t2dm_date).days))
            ckd_enc_id = self.add_encounter(pid, ckd_date, random.choice(ENC_AMBA))
            self.add_condition(pid, ckd_enc_id, ckd_date, C_CKD)
        if random.random() < 0.15:
            cvd_date = self._jitter(t2dm_date, 180, min(730, (index_date - t2dm_date).days))
            cvd_enc_id = self.add_encounter(pid, cvd_date, random.choice(ENC_AMBA))
            self.add_condition(pid, cvd_enc_id, cvd_date, C_CVD)
            self.add_medication(
                pid,
                cvd_enc_id,
                cvd_date,
                ("897399", "aspirin 81 MG Oral Tablet"),
                reason_code=C_CVD[0],
                reason_desc=C_CVD[1],
            )

        if random.random() < 0.25:
            for _ in range(random.randint(1, 2)):
                bl_span = (index_date - t2dm_date).days
                ed_days = random.randint(1, max(1, bl_span - 1))
                ed_date = t2dm_date + timedelta(days=ed_days)
                if ed_date < index_date:
                    self.add_encounter(pid, ed_date, ENC_ED)

        idx_enc_id = self.add_encounter(pid, index_date, random.choice(ENC_AMBA))
        glp1_drug = random.choice(GLP1)
        fu_days = random.randint(365, 730)
        self.add_medication(
            pid,
            idx_enc_id,
            index_date,
            glp1_drug,
            stop=index_date + timedelta(days=fu_days),
            reason_code=C_T2DM[0],
            reason_desc=C_T2DM[1],
        )

        fu_mandatory = self._jitter(index_date, 180, 240)
        fu_enc_id = self.add_encounter(pid, fu_mandatory, random.choice(ENC_AMBA))
        if random.random() < 0.85:
            self.add_observation(
                pid, fu_enc_id, fu_mandatory, OBS_HBA1C, round(random.uniform(5.5, 9.0), 1)
            )
        if random.random() < 0.85:
            self.add_observation(
                pid, fu_enc_id, fu_mandatory, OBS_BMI, round(random.uniform(24.0, 40.0), 1)
            )

        fu_visit = index_date + timedelta(days=90)
        while fu_visit <= index_date + timedelta(days=fu_days):
            if abs((fu_visit - fu_mandatory).days) > 30:
                self.add_encounter(pid, fu_visit, random.choice(ENC_AMBA))
            fu_visit += timedelta(days=90)

        if random.random() < 0.35:
            n_ed = random.choices([1, 2, 3, 4], weights=[0.6, 0.25, 0.10, 0.05])[0]
            for _ in range(n_ed):
                ed_days = random.randint(1, min(fu_days, 540))
                self.add_encounter(pid, index_date + timedelta(days=ed_days), ENC_ED)
        if random.random() < 0.12:
            ip_days = random.randint(1, min(fu_days, 540))
            self.add_encounter(pid, index_date + timedelta(days=ip_days), ENC_IP)

        return pid

    def build_excluded_t1dm(self, index_date: date, birth_date: date) -> str:
        pid = self._uid()
        self.add_patient(pid, birth_date)
        bl_date = index_date - timedelta(days=random.randint(400, 800))
        bl_enc_id = self.add_encounter(pid, bl_date, random.choice(ENC_AMBA))
        self.add_condition(pid, bl_enc_id, bl_date, C_T1DM)
        self.add_condition(pid, bl_enc_id, bl_date, C_T2DM)
        idx_enc_id = self.add_encounter(pid, index_date, random.choice(ENC_AMBA))
        self.add_medication(
            pid,
            idx_enc_id,
            index_date,
            random.choice(GLP1),
            reason_code=C_T1DM[0],
            reason_desc=C_T1DM[1],
        )
        self.add_encounter(pid, index_date + timedelta(days=200), random.choice(ENC_AMBA))
        return pid

    def build_excluded_gdm(self, birth_date: date) -> str:
        pid = self._uid()
        self.add_patient(pid, birth_date)
        gdm_date = date(random.randint(2015, 2022), random.randint(1, 12), 1)
        bl_enc_id = self.add_encounter(pid, gdm_date - timedelta(days=500), random.choice(ENC_AMBA))
        self.add_condition(pid, bl_enc_id, gdm_date - timedelta(days=500), C_T2DM)
        gdm_enc_id = self.add_encounter(pid, gdm_date, random.choice(ENC_AMBA))
        self.add_condition(pid, gdm_enc_id, gdm_date, C_GDM)
        idx_enc_id = self.add_encounter(pid, gdm_date + timedelta(days=30), random.choice(ENC_AMBA))
        self.add_medication(pid, idx_enc_id, gdm_date + timedelta(days=30), random.choice(GLP1))
        self.add_encounter(pid, gdm_date + timedelta(days=250), random.choice(ENC_AMBA))
        return pid

    def build_excluded_no_baseline(self, index_date: date, birth_date: date) -> str:
        pid = self._uid()
        self.add_patient(pid, birth_date)
        t2dm_date = index_date - timedelta(days=random.randint(100, 300))
        enc_id = self.add_encounter(pid, t2dm_date, random.choice(ENC_AMBA))
        self.add_condition(pid, enc_id, t2dm_date, C_T2DM)
        idx_enc_id = self.add_encounter(pid, index_date, random.choice(ENC_AMBA))
        self.add_medication(
            pid,
            idx_enc_id,
            index_date,
            random.choice(GLP1),
            reason_code=C_T2DM[0],
            reason_desc=C_T2DM[1],
        )
        self.add_encounter(pid, index_date + timedelta(days=200), random.choice(ENC_AMBA))
        return pid

    def build_excluded_no_followup(self, index_date: date, birth_date: date) -> str:
        pid = self._uid()
        self.add_patient(pid, birth_date)
        bl_date = index_date - timedelta(days=random.randint(400, 700))
        bl_enc_id = self.add_encounter(pid, bl_date, random.choice(ENC_AMBA))
        self.add_condition(pid, bl_enc_id, bl_date, C_T2DM)
        idx_enc_id = self.add_encounter(pid, index_date, random.choice(ENC_AMBA))
        self.add_medication(pid, idx_enc_id, index_date, random.choice(GLP1))
        self.add_encounter(
            pid,
            index_date + timedelta(days=random.randint(14, 90)),
            random.choice(ENC_AMBA),
        )
        return pid

    def build_no_glp1(self, birth_date: date) -> str:
        pid = self._uid()
        self.add_patient(pid, birth_date)
        t2dm_date = date(random.randint(2005, 2015), random.randint(1, 12), 1)
        enc_id = self.add_encounter(pid, t2dm_date, random.choice(ENC_AMBA))
        self.add_condition(pid, enc_id, t2dm_date, C_T2DM)
        self.add_medication(
            pid,
            enc_id,
            t2dm_date,
            random.choice(DM_MEDS),
            reason_code=C_T2DM[0],
            reason_desc=C_T2DM[1],
        )
        visit = t2dm_date + timedelta(days=90)
        for _ in range(random.randint(2, 8)):
            enc_id2 = self.add_encounter(pid, visit, random.choice(ENC_AMBA))
            if random.random() < 0.5:
                self.add_observation(
                    pid, enc_id2, visit, OBS_HBA1C, round(random.uniform(6.5, 9.5), 1)
                )
            visit += timedelta(days=90 + random.randint(-15, 15))
        return pid

    def build_general_population(self, birth_date: date) -> str:
        pid = self._uid()
        self.add_patient(pid, birth_date)
        base = birth_date + timedelta(days=random.randint(730, 5000))
        enc_id = self.add_encounter(pid, base, random.choice(ENC_AMBA))
        possible = [C_HTN, C_CKD, C_CVD, C_AST, C_HYPO, C_BACK]
        n_conds = random.randint(0, 3)
        for cond in random.sample(possible, min(n_conds, len(possible))):
            self.add_condition(pid, enc_id, base, cond)
        for _ in range(random.randint(0, 4)):
            visit = base + timedelta(days=random.randint(30, 1000))
            enc_id2 = self.add_encounter(pid, visit, random.choice(ENC_AMBA))
            if random.random() < 0.3:
                self.add_observation(
                    pid, enc_id2, visit, OBS_BMI, round(random.uniform(18.5, 35.0), 1)
                )
        if random.random() < 0.10:
            ed_date = base + timedelta(days=random.randint(0, 1000))
            self.add_encounter(pid, ed_date, ENC_ED)
        return pid

    # ── CSV output ────────────────────────────────────────────────────────────

    def write_csv(self, output_dir: Path, filename: str, rows: list[dict]) -> int:
        if not rows:
            print(f"  WARNING: No rows for {filename}", file=sys.stderr)
            return 0
        path = output_dir / filename
        with open(path, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
        print(f"  Wrote {len(rows):>7,} rows → {path}")
        return len(rows)


# ── CLI ───────────────────────────────────────────────────────────────────────


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate custom synthetic CSV files in Synthea-compatible format. "
            "NOT produced by the Synthea Java tool."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/raw"),
        help="Directory to write CSV files into (default: data/raw).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility (default: 42).",
    )
    parser.add_argument(
        "--population",
        type=int,
        default=2000,
        help=(
            "Approximate total population size (default: 2000). "
            "The enrolled cohort is ~21%% of this number; the remainder are "
            "excluded patients and general-population records."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing CSV files without prompting.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()

    output_dir: Path = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Guard against accidental overwrite
    if not args.force:
        existing = [
            f
            for f in [
                "patients.csv",
                "encounters.csv",
                "conditions.csv",
                "medications.csv",
                "observations.csv",
            ]
            if (output_dir / f).exists()
        ]
        if existing:
            print(
                f"ERROR: {len(existing)} CSV file(s) already exist in {output_dir}:\n"
                + "\n".join(f"  {f}" for f in existing)
                + "\nRe-run with --force to overwrite.",
                file=sys.stderr,
            )
            sys.exit(1)

    random.seed(args.seed)

    # Scale group sizes proportionally to --population (baseline 2000)
    scale = args.population / 2000.0
    n_enrolled = max(1, round(420 * scale))
    n_t1dm = max(1, round(40 * scale))
    n_gdm = max(1, round(30 * scale))
    n_no_bl = max(1, round(40 * scale))
    n_no_fu = max(1, round(40 * scale))
    n_no_glp1 = max(1, round(200 * scale))
    n_general = max(1, round(1230 * scale))

    print(
        "Generating custom synthetic patient population\n"
        f"  Output dir : {output_dir}\n"
        f"  Seed       : {args.seed}\n"
        f"  Population : ~{args.population} total\n"
        "NOTE: This is NOT Synthea output — see module docstring."
    )

    gen = _Generator()
    INDEX_START = date(2010, 1, 1)
    INDEX_END = date(2022, 6, 30)

    def rand_index() -> date:
        return INDEX_START + timedelta(days=random.randint(0, (INDEX_END - INDEX_START).days))

    def rand_birth(index_date: date, age_lo: int, age_hi: int) -> date:
        age = random.randint(age_lo, age_hi)
        return index_date - timedelta(days=age * 365 + random.randint(0, 364))

    print(f"  Group A: {n_enrolled} enrolled (T2DM + GLP-1, full baseline & follow-up)…")
    for _ in range(n_enrolled):
        idx = rand_index()
        gen.build_enrolled(idx, rand_birth(idx, 30, 75))

    print(f"  Group B: {n_t1dm} T1DM patients (excluded)…")
    for _ in range(n_t1dm):
        idx = rand_index()
        gen.build_excluded_t1dm(idx, rand_birth(idx, 20, 60))

    print(f"  Group C: {n_gdm} gestational DM patients (excluded)…")
    for _ in range(n_gdm):
        gen.build_excluded_gdm(date(random.randint(1985, 1995), random.randint(1, 12), 1))

    print(f"  Group D: {n_no_bl} patients without adequate baseline (excluded)…")
    for _ in range(n_no_bl):
        idx = rand_index()
        gen.build_excluded_no_baseline(idx, rand_birth(idx, 25, 65))

    print(f"  Group E: {n_no_fu} patients without adequate follow-up (excluded)…")
    for _ in range(n_no_fu):
        idx = date(2022, 7, 1) + timedelta(days=random.randint(0, 100))
        gen.build_excluded_no_followup(idx, rand_birth(idx, 25, 70))

    print(f"  Group F: {n_no_glp1} T2DM patients without GLP-1 (excluded)…")
    for _ in range(n_no_glp1):
        gen.build_no_glp1(date(random.randint(1940, 1985), random.randint(1, 12), 1))

    print(f"  Group G: {n_general} general population patients…")
    for _ in range(n_general):
        gen.build_general_population(date(random.randint(1930, 1990), random.randint(1, 12), 1))

    total = len(gen.patients)
    print(
        f"\nTotal generated: {total:,} patients | "
        f"{len(gen.encounters):,} encounters | "
        f"{len(gen.conditions):,} conditions | "
        f"{len(gen.medications):,} medications | "
        f"{len(gen.observations):,} observations"
    )

    print("\nWriting CSV files…")
    gen.write_csv(output_dir, "patients.csv", gen.patients)
    gen.write_csv(output_dir, "encounters.csv", gen.encounters)
    gen.write_csv(output_dir, "conditions.csv", gen.conditions)
    gen.write_csv(output_dir, "medications.csv", gen.medications)
    gen.write_csv(output_dir, "observations.csv", gen.observations)

    print(
        "\nDone. When ingesting, use:\n"
        f"  evidence-studio ingest --data-source custom_synthetic_demo "
        f"--data-dir {output_dir}"
    )


if __name__ == "__main__":
    main()
